modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3.0"

issueTrackerURL = "https://github.com/62832/ArsEnergique/issues"
displayURL = "https://github.com/62832/ArsEnergique"

[[mods]]
modId = "arseng"
version = "${version}"
displayName = "Ars Énergistique"
authors = "90, dkmk100"
description = '''Bringing magic to the digital age.
Adds digital source storage, P2P transport and various other cross-compatibility improvements to Ars Nouveau and AE2.'''

[[dependencies]]
modId = "ae2"
mandatory = true
versionRange = "[15,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies]]
modId = "ars_nouveau"
mandatory = true
versionRange = "[4.6,)"
ordering = "AFTER"
side = "BOTH"
