modLoader="javafml"
loaderVersion="${loaderVersion}"
license="LGPLv3.0"

issueTrackerURL="https://github.com/62832/ArsEnergique/issues"
displayURL="https://github.com/62832/ArsEnergique"

[[mods]]
modId="arseng"
version="${version}"
displayName="Ars Énergistique"
authors="90"
description='''Bringing magic to the digital age.
Adds digital source storage, P2P transport and various other cross-compatibility improvements to Ars Nouveau and AE2.'''

[[dependencies.arseng]]
    modId="ae2"
    mandatory=true
    versionRange = "${ae2Version}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.arseng]]
    modId="ars_nouveau"
    mandatory=true
    versionRange = "${arsVersion}"
    ordering="AFTER"
    side="BOTH"
