modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv3.0"

issueTrackerURL="https://github.com/62832/ArsEnergique/issues"
displayURL="https://github.com/62832/ArsEnergique"

[[mods]]
modId="arseng"
version="${version}"
displayName="Ars Énergistique"
logoFile="logo.png"
credits=""
authors="90"
description='''
Bringing magic to the digital age.

Adds digital source storage, P2P transport and various other cross-compatibility improvements.
'''

[[dependencies.arseng]]
    modId="ae2"
    mandatory=true
    versionRange = "(,13.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.arseng]]
    modId="ars_nouveau"
    mandatory=true
    versionRange = "[3.4.3.235,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.arseng]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arseng]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
