name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Generate data
        run: ./gradlew downloadAssets runData
      - name: Build release files
        id: build
        env:
          ARSENG_VERSION: ${{ github.event.release.tag_name }}
        run: ./gradlew releaseInfo build
      - name: Publish release files
        uses: Kir-Antipov/mc-publish@4db8bd126f74d5e143822181a2b1201308e2c796
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: 905641
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

          modrinth-id: IJI3QuK8
          modrinth-token: ${{ secrets.MODRINTH_API_KEY }}

          version: ${{ steps.build.outputs.MOD_VERSION }}
          game-versions: ${{ steps.build.outputs.MINECRAFT_VERSION }}
          dependencies: |
            ae2(required){curseforge:223794}{modrinth:XxWD5pD3}
            ars_nouveau(required){curseforge:401955}{modrinth:TKB6INcv}
